### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by mrkaban** [DavidoTek/WatchDogSecurity#2]
1) Why can't ClamAV be packaged with your software? The user does not want to press many buttons - he needs everything to be as simple as possible.

2) I tried to check something, but a quick scan and scan of the selected file gives a message about zero scanned files. That is, everything is completed, but I did not scan anything. ClamAV unpacked it into the program folder, as you wrote.

3) For what purpose are you developing a product?
![111](https://user-images.githubusercontent.com/14289360/72221470-a6018600-358d-11ea-8b3e-0ad345c3cd60.jpg)

**Comment by mrkaban** [comment]
Windows 10 x64

**Comment by DavidoTek** [comment]
1. Currently its just a pre-release (mainly for testing purposes), so I didn't include ClamAV.
2. Quick scan currently only works on Linux.
3. I didn't find a nice cross plaform frontend for ClamAV.

**Comment by mrkaban** [comment]
I have a free software website with approximately 1,300 people per day. I am adding free Windows programs to the site from around the Internet. The idea is interesting, since DOS antivirus for Windows is not interesting to anyone.

Are you planning to solve the problem of working on Windows? If it works correctly, I would be glad to add to my site

**Comment by DavidoTek** [comment]
Yes, I've planned to solve the problem and actually I might have found it.

**Comment by DavidoTek** [comment]
The problem is now fixed.
It didn't create the nessesary configuration file to update the ClamAV database.
You need to update the database at least once, preferably before every scan/every day.

https://github.com/DavidoTek/WatchDogSecurity/releases/tag/0.1.1

**Comment by mrkaban** [comment]
It’s the same anyway. I downloaded version 0.1.1, unpacked the specified clamav into it. I started it, I click on the update database button and there is no reaction, the other two are not pressed. I start the scan and again 0 elements are checked.

**Comment by DavidoTek** [comment]
How long did you wait? It takes a while to update the database and there is no notification.
When the database is updated successfully you should see the database version instead of "?".

**Comment by mrkaban** [comment]
For the first time a maximum of a minute, now I specially pressed it and left it for half an hour. No effect.

**Comment by DavidoTek** [comment]
Did it create a freshclam.conf file in the folder where WatchDogSecurity.exe is? What are the contents?

**Comment by mrkaban** [comment]
There is a file, it contains the following:

> DatabaseMirror database.clamav.net

Thank you for trying to help, I close the ticket, I wish you success in the development of the program, but it is not interesting to me.

**Comment by mrkaban** [comment]
I unsubscribe from the ticket.
